### ISSUE TITLE
iterative updates still download full couchdb

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#11]
While #7 is a step in the right direction, the real improvement will be when we only download the full docs from couchdb if they are not in postgres.

Presently, all docs are downloaded in full from couchdb, but they are only added to postgres if they are not already there. For very large couch databases, this is not terribly useful.

**Comment by btbonval** [comment]
#13 is required.

In order to request only the desired docs, a `POST` is required, which is incredibly annoying to do with built-in `http` or `https` modules.

**Comment by btbonval** [comment]
the unit test is really hard to debug.

Given a url without `include_docs`, one with `include_docs=true` and one with `include_docs=false`, perform each of the following tests:

* can passthrough if no override specified. (this should pass with the current code base, and does)
* can set `include_docs=true` no matter the URL. (this should trivially pass when `include_docs=true` and does)
* can set `include_docs=false` no matter the URL. (this should trivially pass when `include_docs=false` but does not)

After examining the output more closely, I notice that one of the errors is pointing to code in the wrong section. For example, the last test in `given false include_docs override` (starting at line 71) is listed as having errored on line 62 (which corresponds to the block of tests for `given true include_docs override`).

Something funky going on, and not in the good sort of funkay way.

**Comment by btbonval** [comment]
Here's the travis output:
https://travis-ci.org/medic/medic-analytics/jobs/94340579

and the relevant code chunk:
https://github.com/medic/medic-analytics/blob/ea69c435d029c882af2572d18b45dd674a60d6e1/test/unit/couchdb.js#L41-L84

**Comment by browndav** [comment]
It doesn't look like the Nock request interceptors are scoped and/or explicitly destroyed in any way. Is it possible that the interceptor from a previously-completed test is getting called, i.e. outliving its lexical scope due to the fact that it probably modifies `http`?

**Comment by btbonval** [comment]
I had considered that. `nock` is doing some black magic which could very well be causing these problems. As far as I can tell, `nock` does not directly modify the `http` object. The `http` object was the actual `http` module, then the `https` module, then the `request` module. I never told `nock` what I'm using. It seems to do something ... dark.

Interestingly it is not a race condition or caused by async mistakes as the errors are precisely the same on my local system and on travis every time. This was my first thought but I don't see much support for it.

**Comment by browndav** [comment]
You might just quickly try to bisect by running one test at a time (from that set of three) and see if they each succeed in isolation.

**Comment by btbonval** [comment]
I actually wonder if the `context()` is breaking things. That might be a good way to find out.

**Comment by btbonval** [comment]
Each `context()` block works as expected if the other blocks are excluded. The first block with no override passes through the URLs as expected, the true override only succeeds when the parameter is already true, the false override only succeeds when the parameter is already false.

I did notice that the tests aren't failing but are actually erroring with "Uncaught AssertionError", and then the `AssertionError` reported is the test in question. The promises need to be handled better at any rate.

I should try to rewrite these so that they're caught properly using `before()` or `beforeEach()`. I rewrote them a few times to get there but ended up with other problems. I will have to try harder.

**Comment by btbonval** [comment]
Apparently fixed weird unit tests in 7f8e7a286db0652fe473f7040ce2e4f66a5f21b8.

I could have swore I did precisely what is in that commit before with weird errors, but whatever, it took this time. Tests pass and fail as expected and all line numbers point at the correct block. The issue was apparently due to leaky promise assertions being caught at arbitrary points in code and getting themselves confused. Sorted using `before(done)` and a cache variable to test against.

**Comment by btbonval** [comment]
Query parameters are being problematic with nock. I want to match against URI and _test_ the query parameters, but it seems that the query parameter must be matched. If the wrong parameter is supplied, then a timeout _error_ occurs, which is problematic in a `forEach()`, effectively stopping all tests.

This is the "weird errors" thing I was recollecting in the comment above.

**Comment by btbonval** [comment]
http://stackoverflow.com/questions/27844553/nock-js-how-to-match-any-parameter-combination-in-a-url

**Comment by btbonval** [comment]
The parameter problem with nock noted above:
```
  1) fetchDocs() using POST request when docList is given returns data via promise without modification:
     Error: Nock: No match for request POST http://192.168.10.12:1025/me/_de/me?something= keys%5B0%5D=14c6880c-7e92-4225-8ef4-d074c69943f2&keys%5B1%5D=95942c7b-20eb-41b5-a7f9-ef4a1b250f94&keys%5B2%5D=0a7ca498-3f12-4b74-bb88-f41acf5584ba
```

Since the post body is a POST, it seems weird that nock requires the URL to include the POST body contents, but that appears to be how this is being interpreted.

The other example is just a timeout:
```
  2) fetchDocs() using POST request when docList is given when posting data "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

This should not timeout. It should either pass or fail. Seems like an async not getting caught right.

**Comment by btbonval** [comment]
request body filtering is probably the key to the first problem.
https://github.com/pgte/nock#request-body-filtering

The second problem is probably due to the code erroring and thus failing to ever call `done()`.

**Comment by btbonval** [comment]
inclusion of `filteringRequestBody()` leads to
```
  1) fetchDocs() using POST request when docList is given returns data via promise without modification:
     Uncaught TypeError: undefined is not a function
      at Array.filter (native)
```

as though `filteringRequestBody()` is not actually a function. It was added to nock a long time ago and as far as I can tell the docs were updated in November 2015 but no actual code was changed for it. I'll try to get a newer version but I don't think this error should be showing up.

**Comment by btbonval** [comment]
As an additional pain point, it looks like MochaTest supports `--full-trace` but `grunt-mocha-test` supports a limited subset of args, not including `--full-trace`.

So I'm basically guess-and-checking.

**Comment by btbonval** [comment]
I made up a function name to check the error. Only a single failure shows up:
```
  1 failing

  1) fetchDocs() using POST request when docList is given "before each" hook:
     TypeError: undefined is not a function
      at Context.<anonymous> (test/unit/couchdb.js:168:10)
```

This is substantially different from the error when I use `filteringRequestBody()`. The issue is not that `filteringRequestBody()` is missing, but rather than some funky error is happening likely due to the attempted execution of the filter input into `filteringRequestBody()`, though that filter looks just like `filteringPath()` (which works).

**Comment by btbonval** [comment]
`filteringRequestBody()` must return a string and not an object. Guess and checked my way into that. `JSON.stringify` to the rescue.

**Comment by btbonval** [comment]
The JSON data passed in is mangled in all kinds of ways. Unclear whether it is nock mangling this or my own code.

Down to a single true failure at any rate:
```
  1) fetchDocs() using POST request when docList is given when posting data posts data without modification:

      AssertionError: expected 'keys%5B0%5D=14c6880c-7e92-4225-8ef4-d074c69943f2&keys%5B1%5D=95942c7b-20eb-41b5-a7f9-ef4a1b250f94&keys%5B2%5D=0a7ca498-3f12-4b74-bb88-f41acf5584ba' to deeply equal '{"keys":["14c6880c-7e92-4225-8ef4-d074c69943f2","95942c7b-20eb-41b5-a7f9-ef4a1b250f94","0a7ca498-3f12-4b74-bb88-f41acf5584ba"]}'
      + expected - actual

      -keys%5B0%5D=14c6880c-7e92-4225-8ef4-d074c69943f2&keys%5B1%5D=95942c7b-20eb-41b5-a7f9-ef4a1b250f94&keys%5B2%5D=0a7ca498-3f12-4b74-bb88-f41acf5584ba
      +{"keys":["14c6880c-7e92-4225-8ef4-d074c69943f2","95942c7b-20eb-41b5-a7f9-ef4a1b250f94","0a7ca498-3f12-4b74-bb88-f41acf5584ba"]}
```

**Comment by btbonval** [comment]
fun fact, a search for "http post body json" reveals that posting JSON as the body of text is not as trivial as I would think for a great many backends.

**Comment by btbonval** [comment]
Actually this is probably being done client side by the request lib.
```
form - when passed an object or a querystring, this sets body to a querystring representation of value, and adds Content-type: application/x-www-form-urlencoded header. When passed no options, a FormData instance is returned (and is piped to request). See "Forms" section above.
```

**Comment by btbonval** [comment]
unit tests and code written. all tests pass, including integration, locally.

problem is I haven't integrated this feature.

next step: rewrite the integration piece. need to:
* request all doc UUIDs from webapp.
* filter all UUIDs to return only those not in postgres using `couchiter.skipExistingInPG` by passing in all doc UUIDs and postgres info
* post a request for `include_docs` POSTing the doc list above using `cdbfuncs.fetchDocs` by passing in `include_docs=true` and the above UUID list as `postBody`
* profit

**Comment by btbonval** [comment]
I might be missing a piece where I parse JSON text. I had some assumption these objects would be stringified and parsed automagically by `request` but this is not the case. If I run into any problems with the next step, this is probably the thing to look for.

**Comment by btbonval** [comment]
I realize now that I have no particular integration test to distinguish the current result from the desired result when getting partial requests. As far as integration is concerned, the resulting database is populated either way.

The iterative test currently consists of an initial fetch with an artificial doc limit imposed onto the URL and then a second fetch with no limit. The current code will fetch the full contents of all documents including those from the initial fetch, while this enhancement will request only full contents of missing documents.

It seems like I need to write one more integration test which checks whether any doc contents from the initial fetch are repeated in the second fetch.

**Comment by btbonval** [comment]
Current integration tests look strictly at what is in couch and what is in postgres, without examining the underlying process, to ensure the replication occurred as expected.

This modification does not fit under that style of existing test. It's a bit novel in that it does need to examine the underlying process somehow. I'm not sure how to snoop that in any obvious way.

**Comment by btbonval** [comment]
from last night, while GitHub was down:

It turns out this might be easier to test than I thought. The current test's iteration code requested a mutually exclusive chunk of documents. When modified to request all docs, then indeed all docs are added, so the total records end up being 1.5x as expected (half on the base call, then the full set on the second call instead of half).

It looks like requesting all docs in integration is the way to update the integration testing. That causes the current iterative step testing to go red, and the new feature should only fetch the necessary docs bringing it to back to green.

**Comment by btbonval** [comment]
above comment was addressed in commit https://github.com/medic/medic-analytics/commit/764a59facf3f96924e934e82b750ac987da823e6

**Comment by btbonval** [comment]
from last night:

Good progress. Everything is sorted except integration. I must have messed up the format to request specific UUID/REVs by POST.

https://wiki.apache.org/couchdb/HTTP_Bulk_Document_API#Modify_Multiple_Documents_With_a_Single_Request

```
'{"keys":["bar","baz"]}'
```

no rev specification?

**Comment by btbonval** [comment]
I am concerned the lack of revs means that updated docs will only return the newest rev. This will not be a proper mirror and could break integration testing if the test database has any docs with the same UUID but different rev.

Honestly I don't know what rev does. I assume it is revision tracking for updates against an existing doc, and bulk fetch would only get the most recent.

It might be a non-issue as I might not understand how revs work or we might need to specify that `medic-data` can not contain docs with updates. Mirroring old revisions is probably not helpful for any work being performed in postgres, so from a feature standpoint, it's probably fine.

**Comment by btbonval** [comment]
I implemented the POST of keys, and it seems to be ignored. All tests pass except one. All docs are moved, but some are duplicated. It's back to 1.5x the expected docs, so 0.5x on base and 1x instead of 0.5x on iterative update.

I need to test this by hand somehow.
