### ISSUE TITLE
add coverage instrumentation using istanbul

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#12]
Istanbul:
http://gotwarlost.github.io/istanbul/

Grunt-Istanbul:
https://github.com/taichi/grunt-istanbul

If medic has an account with Coverall, Coverall-Istanbul-TravisCI can be mixed together like this:
http://thecodebarbarian.com/2015/02/13/travis_coveralls

**Comment by btbonval** [comment]
This module utilizes almost entirely promise-based logic. It turns out coverage tools aren't all created equal and might not necessarily handle promises.

Example QA regarding the subject on SO.
http://stackoverflow.com/questions/23733108/code-coverage-for-node-js-project-using-q-promises

**Comment by SCdF** [comment]
NB: I'm going to raise tickets about making sure we have tests that cover core functionality and logic branches etc. However, I'm not convinced that code coverage is as useful as people say it is (especially when you take into account the subtleties and potentially misleading aspects of code coverage vs. branch coverage etc).

If we at some point decide that it's important at the Medic level (ie we want to do it for medic-webapp and medic-api) then we can revisit it.
