### ISSUE TITLE
preexisting database table is a problem for local integration testing

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#15]
integration testing fails if the table is preexisting. this is fine for Travis, where postgres will always be fresh. it's mildly annoying for local testing, because I sometimes forget to clear the database. Worth mentioning in README if not outright detecting before running integration tests.

**Comment by btbonval** [comment]
This is due to a change in assumptions where the database used to get nuked prior to entry. The change to iterative updates no longer cares if the database is preexisting or not, but some of the test code fails a bit hard as it still assumes empty.

**Comment by SCdF** [comment]
This will be fixed by the medic/medic-webapp#2124 branch.
