### ISSUE TITLE
replace shared connection with tasks

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#16]
> NOTE: With the addition of Tasks, use of shared connections directly is no longer necessary. It is recommended that you use Tasks instead, as they are much easier to use.

https://github.com/vitaly-t/pg-promise#shared-connections
https://github.com/vitaly-t/pg-promise#tasks

**Comment by btbonval** [comment]
I have divided my queries into individual promises.

It looks like tasks manage queries but not promises, similar to transactions.

It is not obvious how to make use of my promises within the task/tx structure.

**Comment by btbonval** [comment]
This might be a larger project of restructuring my basic assumptions of division of labor that the promises handle, for example, maybe they don't all `return db.query(...)` or something.

**Comment by btbonval** [comment]
Actually, transactions might work quite well. Each "promise" is returning `db.query` where `db` is actually a passed in parameter representing the pg-promise database "thing" (SCO or whatever).

Transactions pass in a parameter (called `t` in the docs) which acts just like a pg-promise database "thing". The transaction isn't executed as a promise until t.batch is called.

Rather than returning the `t.query` from my promise code, each `then` could return `t` itself, which is filtered across my promise code adding queries, ending with a final `then` with `t.batch`. Something like that.

**Comment by btbonval** [comment]
No, I actually need query results to come back so I can filter them in Node code and then move on to the next query.

**Comment by SCdF** [comment]
I'm not convinced we need this: the standard connection pooling in the PG library is good enough IMO. If we come across performance issues we can look at this again.
