### ISSUE TITLE
return number of records updated

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#17]
This would primarily be useful as a debugging tool.

If the import goes impossibly fast, it might be nice to see how many records (if any) were imported. Turns out that it can update 3600some records in about 40 seconds, and on an iterative step, verify no updates needed in less than 1 second. The times surprise me, although it is running against a local webapp.

**Comment by vitaly-t** [comment]
If it is the insert speed, then the following read may help: [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost)

**Comment by btbonval** [comment]
@vitaly-t the time surprised me in a good way. my integration testing takes on the order of minutes, while the actual work being performed is only on the order of tens of seconds. Thanks for the pointer though!

**Comment by vitaly-t** [comment]
You are welcome! Also, I noticed your use of module `pg-format'`, just wanted to point out that the query formatting that's part of `pg-promise` is the most powerful and flexible that you can find, you don't need a separate formatter, that's for sure :)

**Comment by btbonval** [comment]
@vitaly-t Thank for the pointer. I did not realize that. However, this project is written for dealing with medical data in mind, so I wanted to be very explicit in avoiding injection attacks. Hopefully escaping the strings twice does not incur too much performance overhead.

**Comment by vitaly-t** [comment]
pg-promise is impervious to SQL injection because of the way it is implemented. It has a special syntax for accessing SQL names and identifiers, one that doesn't match the syntax for regular variables, which do not have ability to mutate queries.

**Comment by SCdF** [comment]
The code now returns a summary of how many documents were deleted, as well as how many were either updated or created (we don't differentiate).
