### ISSUE TITLE
performance enhancements

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#20]
@vitaly-t pointed out a good reference for boosting pg-promise performance here:
https://github.com/medic/medic-analytics/issues/17#issuecomment-177670217

I haven't looked at my insert code in some time, but it is probably suboptimal.

https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost

**Comment by vitaly-t** [comment]
Actually, the technique suggested here doesn't improve the performance of `pg-promise`, it improves the performance of the IO channel between Node.js and the PostgreSQL server. The library only provides the means.

**Comment by btbonval** [comment]
@vitaly-t Fair distinction.

I have another issue about replacing shared connections with tasks. Would that help performance, or is it mostly a readability concern?

**Comment by vitaly-t** [comment]
It is purely readability + reliability.

**Comment by vitaly-t** [comment]
Also, if you are unsure about the best way to organize your application in terms of the database, have a look at the structure within [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) ;)

**Comment by btbonval** [comment]
This particular line of `INSERT`
https://github.com/medic/medic-analytics/blob/738d4767af87012fb757936eb7ca92610d85c6ad/pgsql.js#L27

is called in a loop here
https://github.com/medic/medic-analytics/blob/738d4767af87012fb757936eb7ca92610d85c6ad/couchiter.js#L57

Seems like exactly what is being addressed in the Performance Boost above.

**Comment by btbonval** [comment]
Of the options, Named Parameter is probably easiest for me to approach in this context.
https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost#using-a-template-with-named-parameters

**Comment by vitaly-t** [comment]
>Seems like exactly what is being addressed in the Performance Boost above.

Almost, it's worse, actually, see [Tasks versus root/direct queries](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries).

**Comment by btbonval** [comment]
@vitaly-t Thanks for that. I knew I needed to change from shared connections to Tasks (#16), but I didn't realize Tasks applied here as well.


I don't remember reading about Tasks when I first wrote most of this code. Either I missed something very important the first time around or it's a newer feature. Regardless, it is worth rewriting important sections of code.

**Comment by vitaly-t** [comment]
Much about this library is fresh, as is the library itself. Tasks make things much cleaner and safer.

**Comment by btbonval** [comment]
I took some time to look at this more closely as I'm adding new code to manage multiple insertions.

I see now it's just a matter of using a single `INSERT` with many `VALUE`s to reduce postgres effort. I also see that is exactly what was said, but I had to see it for myself to understand.

The biggest issue here is managing a clever way to split up very large lists of items into multiple `INSERT`s, each with many `VALUE`s. It shouldn't be hard to work out, but to be precise, one would need to count string length of values as opposed to number of values. I don't think I'm going to be that precise.

**Comment by vitaly-t** [comment]
You don't need to be that precise, you can limit yourself to some 100 values per insert, and your code already will be far more efficient.

**Comment by btbonval** [comment]
@vitaly-t We're dealing with text objects that might be as small as 500 bytes, or as large as 64 megabytes. It might require us to precisely count bytes or string length to avoid overloading node. I caused node to throw out of memory errors a few times already with one of our datasets.

**Comment by vitaly-t** [comment]
In that case you do do a rough calculation, and concatenate inserts based on that ;)

**Comment by btbonval** [comment]
As far as explicit, unique performance enhancements noted in this ticket, the above commit covers this ticket.

It sounds like tasks could also improve performance, but conversion to tasks (or whatever is newer in the pg-promise library) is handled under a different issue (#16)
