### ISSUE TITLE
reduce JSON parsing and stringification

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#21]
I'm running into out-of-memory issues, and JSON parsing has come up.
http://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory

The couch data is returned as a string and parsed at this point in code,  basically to separate out each document from the string:
https://github.com/medic/medic-analytics/blob/738d4767af87012fb757936eb7ca92610d85c6ad/couchiter.js#L6-L9

Each document is then stringified and pushed into postgres:
https://github.com/medic/medic-analytics/blob/738d4767af87012fb757936eb7ca92610d85c6ad/couchiter.js#L55-L57

There might be a way to manipulate this return string by cutting off the `{ 'rows': }` wrapper and then splitting by `,`. Of course, there will probably be other commas inside the docs, and then I start getting close to reinventing the parser wheel.

This might not be something we can get around.

**Comment by btbonval** [comment]
forked from this comment: https://github.com/medic/medic-projects/issues/88#issuecomment-178303849

**Comment by SCdF** [comment]
I don't believe this is relevant as the code around this has changed significantly. If it turns out to be still a problem I'll raise a medic-webapp ticket.
