### ISSUE TITLE
inconsistent parameter order

### ISSUE THREAD

**Issue by btbonval** [medic/medic-analytics#24]
https://github.com/medic/medic-analytics/blob/67823213a650c9ae71bfa9c8367d66fe5f08ffbb/libs/couch2pg/pgfuncs.js#L3
uses `pgsql` SQL module, then `db` pg-promise lib.

All other places use `db`, then `pgsql`.

Just a cleanup note to make this consistent with the rest.

**Comment by SCdF** [comment]
No longer relevant as this file no longer exists.
