### ISSUE TITLE
pg-promise version

### ISSUE THREAD

**Issue by vitaly-t** [medic/medic-analytics#26]
You are probably the only one using such an ancient version of pg-promise.

The current one is 3.3.1, and if you upgrade to it, you will be able to access lots of new features that will make your code much better.

**Comment by btbonval** [comment]
@vitaly-t Yeah, I have many issues on this project which require overhauling existing code. I think it will be a month before I have the bandwidth for any code clean up or overhaul. This is a good issue to keep around when time frees up to clean up.

I have been using your recommendations for new features as much as possible, although now the code is a mess of different styles.

You can think of this like alpha software. Features must come first. The optimizations and cleanup can only happen later. :(

**Comment by vitaly-t** [comment]
For example, you could shrink this code into half: https://github.com/medic/medic-analytics/blob/master/libs/xmlforms/index.js

I would show you how, but you need first upgrade the pg-promise version ;)

**Comment by btbonval** [comment]
Local testing works fine using pg-promise@3.4.3, and TravisCI seemed okay with the change. Above commit takes care of upgrading pg-promise.
